export const ADD_POST = 'ADD_POST';
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const DELETE_POST = 'DELETE_POST';
export const ADD_PHOTO = 'ADD_PHOTO';
export const DOWNLOAD_POSTS = 'DOWNLOAD_POSTS';
export const DOWNLOAD_USERS = 'DOWNLOAD_USERS';
export const SET_CURRENT_PAGE_NUMBER = 'SET_CURRENT_PAGE_NUMBER'
export const USERS_ARE_LOADING = 'USERS_ARE_LOADING'